import turtle

alphabet = turtle.Turtle()
sc = turtle.Screen()
# sc.tracer(False)
turtle.setworldcoordinates(-500, -500, 500, 500)
alphabet.pu()
alphabet.setpos(-500,400)
alphabet.speed(1000)
x,y = -500,400
# turtle.setworldcoordinates(-360, -360, 360, 360)

def putspace(d=50):
    global x
    alphabet.seth(0)
    alphabet.pu()
    alphabet.fd(d)
    alphabet.pd()
    x += d + d

def checkX():
    global x, y
    if x>=400:
        y -= 150
    alphabet.pu()
    alphabet.goto(-500,y)
    x = -500


def drawA():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.bk(50)
    alphabet.lt(90)
    alphabet.fd(50)

def drawB():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.bk(50)
    alphabet.lt(90)
    alphabet.fd(50)
    alphabet.lt(90)
    alphabet.bk(50)
    alphabet.fd(50)

def drawC():
    putspace()
    putspace(50)
    alphabet.seth(0)
    alphabet.bk(50)
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(0)
    alphabet.fd(50)
    alphabet.pu()
    alphabet.seth(-90)
    alphabet.fd(100)

def drawD():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.bk(100)
    alphabet.seth(0)
    alphabet.circle(50,180)
    alphabet.seth(90)
    alphabet.bk(100)
    alphabet.seth(0)
    alphabet.pu()
    alphabet.fd(50)

def drawE():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(0)
    alphabet.fd(60)
    alphabet.pu()
    alphabet.bk(60)
    alphabet.seth(90)
    alphabet.bk(50)
    alphabet.seth(0)
    alphabet.pd()
    alphabet.fd(50)
    alphabet.bk(50)
    alphabet.seth(90)
    alphabet.bk(50)
    alphabet.seth(0)
    alphabet.fd(60)

def drawF():
    putspace()
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(0)
    alphabet.fd(50)
    alphabet.bk(50)
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(0)
    alphabet.fd(60)

def drawG():
    putspace(100)
    alphabet.pu()
    alphabet.seth(-45)
    alphabet.fd(20)
    alphabet.pd()
    alphabet.seth(135)
    alphabet.circle(50,310)
    alphabet.seth(0)
    alphabet.bk(60)
    alphabet.pu()
    alphabet.fd(60)
    alphabet.rt(90)
    alphabet.fd(50)

def drawH():
    putspace()
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.rt(90)
    alphabet.fd(50)
    alphabet.bk(50)
    alphabet.lt(90)
    alphabet.fd(50)
    putspace()
    alphabet.seth(-90)
    alphabet.fd(100)

def drawI():
    putspace()
    alphabet.seth(0)
    alphabet.fd(60)
    alphabet.bk(30)
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(0)
    alphabet.bk(30)
    alphabet.fd(60)
    alphabet.seth(-90)
    alphabet.pu()
    alphabet.fd(100)

def drawJ():
    putspace()
    alphabet.seth(90)
    alphabet.fd(30)
    alphabet.bk(30)
    alphabet.rt(90)
    alphabet.fd(30)
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(0)
    alphabet.bk(30)
    alphabet.fd(60)
    alphabet.seth(-90)
    alphabet.pu()
    alphabet.fd(100)

def drawK():
    putspace()
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(-45)
    alphabet.fd(70)
    alphabet.bk(70)
    alphabet.seth(45)
    alphabet.fd(70)
    alphabet.bk(70)
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.pu()
    alphabet.bk(100)
    alphabet.seth(0)
    alphabet.fd(50)

def drawL():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.bk(100)
    alphabet.seth(0)
    alphabet.fd(50)

def drawM():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(-60)
    alphabet.fd(77)
    alphabet.seth(60)
    alphabet.fd(77)
    alphabet.seth(-90)
    alphabet.fd(100)

def drawN():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.seth(-60)
    alphabet.fd(112)
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.bk(100)

def drawO():
    putspace()
    putspace()
    alphabet.seth(0)
    alphabet.circle(50)

def drawP():
    putspace()
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.bk(50)
    alphabet.seth(0)
    alphabet.circle(25,180)
    alphabet.seth(-90)
    alphabet.fd(100)
    putspace()

def drawQ():
    putspace()
    alphabet.circle(50)
    alphabet.pu()
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(-45)
    alphabet.fd(25)
    alphabet.pd()
    alphabet.fd(50)

def drawR():
    putspace()
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(0)
    alphabet.circle(25,180)
    alphabet.seth(-90)
    alphabet.fd(50)
    alphabet.seth(-60)
    alphabet.fd(57)

def drawS():
    putspace()
    alphabet.fd(30)
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(180)
    alphabet.fd(30)
    alphabet.seth(90)
    alphabet.fd(50)
    alphabet.seth(0)
    alphabet.fd(30)

def drawT():
    putspace()
    alphabet.seth(0)
    alphabet.fd(60)
    alphabet.bk(30)
    alphabet.seth(-90)
    alphabet.fd(100)
    putspace(30)

def drawU():
    putspace()
    alphabet.seth(90)
    alphabet.fd(100)
    alphabet.bk(100)
    alphabet.seth(0)
    alphabet.fd(50)
    alphabet.seth(90)
    alphabet.fd(100)

def drawV():
    putspace()
    alphabet.seth(-70)
    alphabet.fd(102)
    alphabet.seth(70)
    alphabet.fd(102)

def drawW():
    putspace()
    alphabet.seth(-70)
    alphabet.fd(102)
    alphabet.seth(70)
    alphabet.fd(102)
    alphabet.seth(-70)
    alphabet.fd(102)
    alphabet.seth(70)
    alphabet.fd(102)

def drawX():
    putspace()
    alphabet.seth(-60)
    alphabet.fd(104)
    alphabet.bk(52)
    alphabet.seth(60)
    alphabet.fd(52)
    alphabet.bk(104)
    alphabet.pu()
    alphabet.fd(104)

def drawY():
    putspace()
    alphabet.seth(-60)
    alphabet.fd(52)
    alphabet.seth(60)
    alphabet.fd(52)
    alphabet.bk(52)
    alphabet.seth(-90)
    alphabet.fd(50)
    putspace(20)

def drawZ():
    putspace()
    alphabet.seth(0)
    alphabet.fd(60)
    alphabet.bk(60)
    alphabet.seth(60)
    alphabet.fd(117)
    alphabet.seth(180)
    alphabet.fd(60)

sc.bgcolor("white")
alphabet.color("blue")
alphabet.shape("turtle")
alphabet.pensize(10)
# sougata.pu()
# sougata.fd(20)
alphabet.pd()
drawA()
drawB()
drawC()
drawD()
drawE()
drawF()
drawG()
drawH()
drawI()
checkX()
drawJ()
drawK()
drawL()
drawM()
drawN()
drawO()
drawP()
drawQ()
checkX()
drawR()
drawS()
drawT()
drawU()
drawV()
drawW()
drawX()
drawY()
checkX()
drawZ()


alphabet.ht()
# sc.tracer(True)
turtle.done()